name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd rosle-web
          npm install
          
      - name: Build
        run: |
          cd rosle-web
          npm run build

      - name: Test
        run: echo "Token is ${{ secrets.GITHUB_TOKEN }}"
          
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: rosle
          directory: rosle-web/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }} 
